<?php
/**
 * Project: kkmo_sv.
 * Date: 2017/8/6
 * Time: 13:23
 * Copyright (c) 2014-2017 http://iydhp.com All rights reserved.
 */

return [
    [
        'title'       => '服务器',
        'icon'        => 'fa fa-fw fa-newspaper-o',
        'url_type'    => 'module_admin',
        'url_value'   => 'home/index/index',
        'url_target'  => '_self',
        'online_hide' => 0,
        'sort'        => 100,
        'child'       => [
            [
                'title'       => '仪表盘',
                'icon'        => 'fa fa-fw fa-tachometer',
                'url_type'    => 'module_admin',
                'url_value'   => 'home/index/index',
                'url_target'  => '_self',
                'online_hide' => 0,
                'sort'        => 100,
            ],
            [
                'title'       => '系统设置',
                'icon'        => 'fa fa-fw fa-cog',
                'url_type'    => 'module_admin',
                'url_value'   => 'home/index/config',
                'url_target'  => '_self',
                'online_hide' => 0,
                'sort'        => 100,
            ],
            [
                'title'       => '提升服主',
                'icon'        => 'fa fa-fw fa-cog',
                'url_type'    => 'module_admin',
                'url_value'   => 'home/index/fuzhu',
                'url_target'  => '_self',
                'online_hide' => 0,
                'sort'        => 100,
            ],
            [
                'title'       => '服务器管理',
                'icon'        => 'fa fa-fw fa-folder-open-o',
                'url_type'    => 'module_admin',
                'url_value'   => '',
                'url_target'  => '_self',
                'online_hide' => 0,
                'sort'        => 100,
                'child'       => [
                    [
                        'title'       => '服务器类型',
                        'icon'        => 'fa fa-fw fa-list',
                        'url_type'    => 'module_admin',
                        'url_value'   => 'home/category/index',
                        'url_target'  => '_self',
                        'online_hide' => 0,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/add',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/edit',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/delete',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/enable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/disable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '完全控制',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/category/allctr',
                                'url_target'  => '_self',
                                'online_hide' => 1,
                                'sort'        => 100,
                            ],
                        ]
                    ],
                    [
                        'title'       => '服务器列表',
                        'icon'        => 'fa fa-fw fa-plus',
                        'url_type'    => 'module_admin',
                        'url_value'   => 'home/server/index',
                        'url_target'  => '_self',
                        'online_hide' => 0,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '新增',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/add',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '编辑',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/edit',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/delete',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/enable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/disable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '完全控制',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/server/allctr',
                                'url_target'  => '_self',
                                'online_hide' => 1,
                                'sort'        => 100,
                            ],
                        ]
                    ],
                    [
                        'title'       => '服务器审核',
                        'icon'        => 'fa fa-fw fa-book',
                        'url_type'    => 'module_admin',
                        'url_value'   => 'home/verify/index',
                        'url_target'  => '_self',
                        'online_hide' => 0,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '审核',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/verify/verify',
                                'url_target'  => '_self',
                                'online_hide' => 1,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '详情',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/verify/info',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '完全控制',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/verify/allctr',
                                'url_target'  => '_self',
                                'online_hide' => 1,
                                'sort'        => 100,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title'       => '服务器功能',
                'icon'        => 'fa fa-fw fa-suitcase',
                'url_type'    => 'module_admin',
                'url_value'   => '',
                'url_target'  => '_self',
                'online_hide' => 0,
                'sort'        => 100,
                'child'       => [
                    [
                        'title'       => '服务器评价',
                        'icon'        => 'fa fa-fw fa-list',
                        'url_type'    => 'module_admin',
                        'url_value'   => 'home/comment/index',
                        'url_target'  => '_self',
                        'online_hide' => 0,
                        'sort'        => 100,
                        'child'       => [
                            [
                                'title'       => '编辑',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/comment/edit',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '删除',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/comment/delete',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '启用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/comment/enable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '禁用',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/comment/disable',
                                'url_target'  => '_self',
                                'online_hide' => 0,
                                'sort'        => 100,
                            ],
                            [
                                'title'       => '完全控制',
                                'icon'        => '',
                                'url_type'    => 'module_admin',
                                'url_value'   => 'home/comment/allctr',
                                'url_target'  => '_self',
                                'online_hide' => 1,
                                'sort'        => 100,
                            ],
                        ]
                    ],
                ],
            ],
        ]
    ]
];